import gzip
import hashlib
import io
import tarfile

import pytest

from drskill import content, service
from drskill.models import BundledFile, Contributor, Provenance, TokenCost

# Pinned cross-repo vector: generated by the Rails Content::ManifestHash
# implementation for these exact files. Both sides must agree byte for byte.
VECTOR_FILES = [
    {"path": "SKILL.md", "data": b"# Vector\n", "executable": False},
    {"path": "scripts/run.sh", "data": b"#!/bin/sh\necho hi\n", "executable": True},
    {"path": "reference/notes.md", "data": b"Notes.\n", "executable": False},
]
VECTOR_HASH = "sha256:2ce4efb09e8099521c65d4eba3434d52d52a8819d974f201f540c18ed7659ecf"


def test_manifest_hash_matches_the_server_vector():
    assert content.manifest_hash(VECTOR_FILES) == VECTOR_HASH


def test_manifest_hash_is_order_independent():
    assert content.manifest_hash(list(reversed(VECTOR_FILES))) == VECTOR_HASH


def test_manifest_hash_changes_with_content():
    changed = [dict(VECTOR_FILES[0], data=b"different"), *VECTOR_FILES[1:]]
    assert content.manifest_hash(changed) != VECTOR_HASH


def make_skill_dir(tmp_path):
    skill = tmp_path / "my-skill"
    (skill / "scripts").mkdir(parents=True)
    (skill / "SKILL.md").write_bytes(b"# My skill\n")
    (skill / "scripts" / "run.sh").write_bytes(b"#!/bin/sh\n")
    (skill / "scripts" / "run.sh").chmod(0o755)
    return skill


def make_contributor(skill_dir):
    return Contributor(
        id=str(skill_dir / "SKILL.md"),
        kind="skill",
        name="my-skill",
        source=Provenance(kind="unmanaged", source=None),
        scope="project",
        bundled_files=[
            BundledFile(relpath="scripts/run.sh", size=10,
                        content_hash="sha256:" + "ab" * 32, is_text=True, oversize=False)
        ],
        token_cost=TokenCost(catalog_tokens=1, body_tokens=1),
        content_hash="sha256:" + "ab" * 32,
    )


def test_collect_files_reads_the_skill_file_and_bundled_files(tmp_path):
    skill = make_skill_dir(tmp_path)
    files = content.collect_files(make_contributor(skill))
    by_path = {f["path"]: f for f in files}
    assert set(by_path) == {"SKILL.md", "scripts/run.sh"}
    assert by_path["SKILL.md"]["data"] == b"# My skill\n"
    assert not by_path["SKILL.md"]["executable"]
    assert by_path["scripts/run.sh"]["executable"]


def test_pack_produces_a_ustar_tar_the_server_shape_accepts():
    packed = content.pack(VECTOR_FILES)
    with tarfile.open(fileobj=io.BytesIO(packed), mode="r:gz") as tar:
        members = tar.getmembers()
        assert [m.name for m in members] == sorted(f["path"] for f in VECTOR_FILES)
        for member in members:
            assert member.isreg()
        modes = {m.name: m.mode for m in members}
        assert modes["scripts/run.sh"] & 0o111
        assert not modes["SKILL.md"] & 0o111
        run = tar.extractfile("scripts/run.sh").read()
        assert run == b"#!/bin/sh\necho hi\n"


@pytest.fixture
def api(monkeypatch):
    calls = []

    def fake_api_request(method, path, token=None, json_body=None, base_url=None,
                         raw=False, raw_body=None, content_type=None, binary=False):
        calls.append({"method": method, "path": path, "token": token,
                      "raw_body": raw_body, "content_type": content_type,
                      "base_url": base_url})
        response = fake_api_request.responses.get((method, path))
        if isinstance(response, service.ServiceError):
            raise response
        return response or {}

    fake_api_request.responses = {}
    monkeypatch.setattr(service, "api_request", fake_api_request)
    return calls, fake_api_request


def test_upload_skips_the_post_when_the_server_already_has_the_content(api):
    calls, fake = api
    fake.responses[("HEAD", f"/api/v1/content/{VECTOR_HASH}")] = {}
    result = content.upload(VECTOR_FILES, token="drsk_x", base_url="http://svc.test")
    assert result == {"content_hash": VECTOR_HASH, "uploaded": False}
    assert [c["method"] for c in calls] == ["HEAD"]


def test_upload_posts_when_the_head_misses(api):
    calls, fake = api
    fake.responses[("HEAD", f"/api/v1/content/{VECTOR_HASH}")] = service.ServiceError(
        "not_found", "Not found.")
    fake.responses[("POST", "/api/v1/content")] = {"content_hash": VECTOR_HASH,
                                                   "existed": False}
    result = content.upload(VECTOR_FILES, token="drsk_x", base_url="http://svc.test")
    assert result == {"content_hash": VECTOR_HASH, "uploaded": True}
    post = calls[1]
    assert post["content_type"] == "application/gzip"
    assert post["raw_body"] == content.pack(VECTOR_FILES)
    assert post["base_url"] == "http://svc.test"


def test_upload_raises_when_the_server_hash_disagrees(api):
    calls, fake = api
    fake.responses[("HEAD", f"/api/v1/content/{VECTOR_HASH}")] = service.ServiceError(
        "http_error", "HTTP 404")
    fake.responses[("POST", "/api/v1/content")] = {"content_hash": "sha256:" + "00" * 32}
    with pytest.raises(service.ServiceError) as excinfo:
        content.upload(VECTOR_FILES, token="drsk_x", base_url="http://svc.test")
    assert excinfo.value.code == "hash_mismatch"


def test_upload_reraises_errors_that_are_not_a_miss(api):
    calls, fake = api
    fake.responses[("HEAD", f"/api/v1/content/{VECTOR_HASH}")] = service.ServiceError(
        "connection_error", "Could not reach the service")
    with pytest.raises(service.ServiceError) as excinfo:
        content.upload(VECTOR_FILES, token="drsk_x", base_url="http://svc.test")
    assert excinfo.value.code == "connection_error"
    assert len(calls) == 1


# -- download / unpack / write ------------------------------------------------


def test_unpack_round_trips_pack():
    files = content.unpack(content.pack(VECTOR_FILES))
    assert content.manifest_hash(files) == VECTOR_HASH
    by_path = {f["path"]: f for f in files}
    assert by_path["scripts/run.sh"]["executable"]
    assert not by_path["SKILL.md"]["executable"]


def test_unpack_rejects_garbage():
    with pytest.raises(service.ServiceError) as excinfo:
        content.unpack(b"not gzip")
    assert excinfo.value.code == "content_invalid"


def _tar_with_member(name, data=b"x", typeflag=b"0", mode=0o644, size=None):
    """Hand-rolled single-member ustar for attack fixtures tarfile refuses to write."""
    header = bytearray(512)
    header[0:len(name.encode())] = name.encode()
    header[100:108] = f"{mode:07o}\0".encode()
    header[108:116] = b"0000000\0"
    header[116:124] = b"0000000\0"
    header[124:136] = f"{size if size is not None else len(data):011o}\0".encode()
    header[136:148] = f"{0:011o}\0".encode()
    header[148:156] = b" " * 8
    header[156:157] = typeflag
    header[257:263] = b"ustar\0"
    header[263:265] = b"00"
    checksum = sum(header)
    header[148:156] = f"{checksum:06o}\0 ".encode()
    padding = (512 - len(data) % 512) % 512
    body = bytes(header) + data + b"\0" * padding + b"\0" * 1024
    buffer = io.BytesIO()
    with gzip.GzipFile(fileobj=buffer, mode="wb", mtime=0) as gz:
        gz.write(body)
    return buffer.getvalue()


@pytest.mark.parametrize("name,typeflag", [
    ("evil", b"2"),          # symlink
    ("evil", b"1"),          # hard link
    ("/etc/passwd", b"0"),   # absolute path
    ("../evil", b"0"),       # dot-dot path
])
def test_unpack_rejects_unsafe_members(name, typeflag):
    with pytest.raises(service.ServiceError) as excinfo:
        content.unpack(_tar_with_member(name, typeflag=typeflag))
    assert excinfo.value.code == "content_invalid"


def test_download_verifies_the_manifest_hash(api):
    calls, fake = api
    fake.responses[("GET", f"/api/v1/content/{VECTOR_HASH}")] = content.pack(VECTOR_FILES)
    files = content.download(VECTOR_HASH, token="drsk_x", base_url="http://svc.test")
    assert content.manifest_hash(files) == VECTOR_HASH

    wrong = "sha256:" + "00" * 32
    fake.responses[("GET", f"/api/v1/content/{wrong}")] = content.pack(VECTOR_FILES)
    with pytest.raises(service.ServiceError) as excinfo:
        content.download(wrong, token="drsk_x", base_url="http://svc.test")
    assert excinfo.value.code == "hash_mismatch"


def test_write_skill_and_read_dir_round_trip(tmp_path):
    target = tmp_path / "store" / "vector"
    content.write_skill(VECTOR_FILES, target)
    assert (target / "SKILL.md").read_bytes() == b"# Vector\n"
    assert (target / "scripts" / "run.sh").stat().st_mode & 0o111
    assert content.manifest_hash(content.read_dir(target)) == VECTOR_HASH


def test_write_skill_replaces_an_existing_directory_atomically(tmp_path):
    target = tmp_path / "vector"
    content.write_skill(VECTOR_FILES, target)
    (target / "stale.md").write_bytes(b"old")
    content.write_skill(VECTOR_FILES, target)
    assert not (target / "stale.md").exists()
    assert content.manifest_hash(content.read_dir(target)) == VECTOR_HASH
    assert not list(tmp_path.glob(".*tmp*"))
