import gzip
import hashlib
import io
import tarfile

import pytest

from drskill import content, service
from drskill.models import BundledFile, Contributor, Provenance, TokenCost

# Pinned cross-repo vector: generated by the Rails Content::ManifestHash
# implementation for these exact files. Both sides must agree byte for byte.
VECTOR_FILES = [
    {"path": "SKILL.md", "data": b"# Vector\n", "executable": False},
    {"path": "scripts/run.sh", "data": b"#!/bin/sh\necho hi\n", "executable": True},
    {"path": "reference/notes.md", "data": b"Notes.\n", "executable": False},
]
VECTOR_HASH = "sha256:2ce4efb09e8099521c65d4eba3434d52d52a8819d974f201f540c18ed7659ecf"


def test_manifest_hash_matches_the_server_vector():
    assert content.manifest_hash(VECTOR_FILES) == VECTOR_HASH


def test_manifest_hash_is_order_independent():
    assert content.manifest_hash(list(reversed(VECTOR_FILES))) == VECTOR_HASH


def test_manifest_hash_changes_with_content():
    changed = [dict(VECTOR_FILES[0], data=b"different"), *VECTOR_FILES[1:]]
    assert content.manifest_hash(changed) != VECTOR_HASH


def make_skill_dir(tmp_path):
    skill = tmp_path / "my-skill"
    (skill / "scripts").mkdir(parents=True)
    (skill / "SKILL.md").write_bytes(b"# My skill\n")
    (skill / "scripts" / "run.sh").write_bytes(b"#!/bin/sh\n")
    (skill / "scripts" / "run.sh").chmod(0o755)
    return skill


def make_contributor(skill_dir):
    return Contributor(
        id=str(skill_dir / "SKILL.md"),
        kind="skill",
        name="my-skill",
        source=Provenance(kind="unmanaged", source=None),
        scope="project",
        bundled_files=[
            BundledFile(relpath="scripts/run.sh", size=10,
                        content_hash="sha256:" + "ab" * 32, is_text=True, oversize=False)
        ],
        token_cost=TokenCost(catalog_tokens=1, body_tokens=1),
        content_hash="sha256:" + "ab" * 32,
    )


def test_collect_files_reads_the_skill_file_and_bundled_files(tmp_path):
    skill = make_skill_dir(tmp_path)
    files = content.collect_files(make_contributor(skill))
    by_path = {f["path"]: f for f in files}
    assert set(by_path) == {"SKILL.md", "scripts/run.sh"}
    assert by_path["SKILL.md"]["data"] == b"# My skill\n"
    assert not by_path["SKILL.md"]["executable"]
    assert by_path["scripts/run.sh"]["executable"]


def test_pack_produces_a_ustar_tar_the_server_shape_accepts():
    packed = content.pack(VECTOR_FILES)
    with tarfile.open(fileobj=io.BytesIO(packed), mode="r:gz") as tar:
        members = tar.getmembers()
        assert [m.name for m in members] == sorted(f["path"] for f in VECTOR_FILES)
        for member in members:
            assert member.isreg()
        modes = {m.name: m.mode for m in members}
        assert modes["scripts/run.sh"] & 0o111
        assert not modes["SKILL.md"] & 0o111
        run = tar.extractfile("scripts/run.sh").read()
        assert run == b"#!/bin/sh\necho hi\n"


@pytest.fixture
def api(monkeypatch):
    calls = []

    def fake_api_request(method, path, token=None, json_body=None, base_url=None,
                         raw=False, raw_body=None, content_type=None):
        calls.append({"method": method, "path": path, "token": token,
                      "raw_body": raw_body, "content_type": content_type,
                      "base_url": base_url})
        response = fake_api_request.responses.get((method, path))
        if isinstance(response, service.ServiceError):
            raise response
        return response or {}

    fake_api_request.responses = {}
    monkeypatch.setattr(service, "api_request", fake_api_request)
    return calls, fake_api_request


def test_upload_skips_the_post_when_the_server_already_has_the_content(api):
    calls, fake = api
    fake.responses[("HEAD", f"/api/v1/content/{VECTOR_HASH}")] = {}
    result = content.upload(VECTOR_FILES, token="drsk_x", base_url="http://svc.test")
    assert result == {"content_hash": VECTOR_HASH, "uploaded": False}
    assert [c["method"] for c in calls] == ["HEAD"]


def test_upload_posts_when_the_head_misses(api):
    calls, fake = api
    fake.responses[("HEAD", f"/api/v1/content/{VECTOR_HASH}")] = service.ServiceError(
        "not_found", "Not found.")
    fake.responses[("POST", "/api/v1/content")] = {"content_hash": VECTOR_HASH,
                                                   "existed": False}
    result = content.upload(VECTOR_FILES, token="drsk_x", base_url="http://svc.test")
    assert result == {"content_hash": VECTOR_HASH, "uploaded": True}
    post = calls[1]
    assert post["content_type"] == "application/gzip"
    assert post["raw_body"] == content.pack(VECTOR_FILES)
    assert post["base_url"] == "http://svc.test"


def test_upload_raises_when_the_server_hash_disagrees(api):
    calls, fake = api
    fake.responses[("HEAD", f"/api/v1/content/{VECTOR_HASH}")] = service.ServiceError(
        "http_error", "HTTP 404")
    fake.responses[("POST", "/api/v1/content")] = {"content_hash": "sha256:" + "00" * 32}
    with pytest.raises(service.ServiceError) as excinfo:
        content.upload(VECTOR_FILES, token="drsk_x", base_url="http://svc.test")
    assert excinfo.value.code == "hash_mismatch"


def test_upload_reraises_errors_that_are_not_a_miss(api):
    calls, fake = api
    fake.responses[("HEAD", f"/api/v1/content/{VECTOR_HASH}")] = service.ServiceError(
        "connection_error", "Could not reach the service")
    with pytest.raises(service.ServiceError) as excinfo:
        content.upload(VECTOR_FILES, token="drsk_x", base_url="http://svc.test")
    assert excinfo.value.code == "connection_error"
    assert len(calls) == 1
